config/routes.rb
Rails.application.routes.draw do
  root :to => "janken#input"
  
  get "janken/input"
  
  get "/jankens/:id(.:format)" => "janken#battle" 
  
  post "janken/update"
  
  post "janken/update_battle"

  get "/auth/:provider/callback" => "sessions#create"
  
  get "/signout" => "sessions#destroy"
  

end

app/models/janken.rb
class Janken < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :signed_in?
  
  private
  def signed_in?
    true if session[:oauth_token]
  end
end

app/controllers/janken_controller.rb
class JankenController < ApplicationController
  def tweet_it
    return true
  end
  
  def input
    if session[:url] != nil
      redirect_url = session[:url]
      session[:url] = nil
      redirect_to redirect_url
    end
  end
  
  def battle
    # Battle データの読み込み
    temp_janken = Janken.find_by_id(params[:id])
    @user = temp_janken.user
    @enemy = temp_janken.enemy
    @id = params["id"]
    if !signed_in?
      session[:url] = request.base_url() + '/jankens/' + @id.to_s
    end
  end

  def update
    if signed_in?
      enemy = params[:enemyname]
      userhand = params[:userhand]

      # Modelオブジェクトに登録する
      @janken_id = nil
      Janken.new do |janken|
        janken.user = session[:username]
        janken.enemy = enemy
        janken.userhand = userhand
        janken.enemyhand = 0
        janken.judge = 0
        janken.save
        @janken_id = janken.id
      end
      
      # Tweetを送る
      client = Twitter::REST::Client.new do |config|
        config.consumer_key = ENV["CONSUMER_KEY"]
        config.consumer_secret = ENV["CONSUMER_SECRET"] 
        config.access_token = session[:oauth_token]
        config.access_token_secret = session[:oauth_token_secret]
      end
      uri = request.base_url() + '/jankens/' + @janken_id.to_s
      tweet = "@" + enemy + ' じゃんけん勝負が申し込まれました ' + uri + " #ついったぽい"
      if tweet_it == true
        client.update(tweet)
      else
        print tweet
      end
      @result = :success
    else
      session[:enemyname] = params[:enemyname]
      session[:userhand] = params[:userhand]
      @result = :not_signed_in
      redirect_to request.base_url + '/auth/twitter'
    end
  end
  
  def update_battle
    # Battle データの読み込み
    temp_janken = Janken.find_by_id(params[:id])
    @url = request.base_url() + '/jankens/' + params[:id].to_s
    @user = temp_janken.user
    @enemy = temp_janken.enemy
    print @enemy
    if signed_in?
      if @enemy.strip.downcase != session[:username].strip.downcase
        redirect_to request.base_url
      end
      session[:url] = nil
      enemy = true
      # 勝敗情報を登録する
      result = judge_func(temp_janken.userhand, params[:enemyhand])
      temp_janken.enemyhand = params[:enemyhand]
      temp_janken.judge = result
      temp_janken.save
      
      # Tweetを送る
      client = Twitter::REST::Client.new do |config|
        config.consumer_key = ENV["CONSUMER_KEY"]
        config.consumer_secret = ENV["CONSUMER_SECRET"] 
        config.access_token = session[:oauth_token]
        config.access_token_secret = session[:oauth_token_secret]
      end
      
      if result == 0
        message = ' この勝負、あいこ '
      elsif result == 1
        message = ' この勝負、@' + @enemy + ' の勝ち。 '
      elsif result == 2
        message = ' この勝負、@' + @user + ' の勝ち。 ' 
      else
        message = ' この勝負、なにかおかしいぞ？ '
      end
      uri = request.base_url()
      tweet = "@" + @user + ' VS @' + @enemy + message + uri + " #ついったぽい"
      if tweet_it == true
        client.update(tweet)
      else
        print tweet
      end
      
      @result = :success
    else
      session[:url] = @url
      @result = :not_signed_in
      redirect_to request.base_url + '/auth/twitter'
    end
  end
  
  def judge_func(user, enemy)
    # user is => win:2 lose:1 even:0
    print user
    print enemy
    judge_param = (user.to_i - enemy.to_i + 3) % 3
    return judge_param
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    session[:oauth_token] = auth.credentials.token
    session[:oauth_token_secret] = auth.credentials.secret
    session[:username] = auth.extra.access_token.params[:screen_name]
    
    if session[:url] == nil
      redirect_to root_url, :notice => "Signed in"
    else
      redirect_to session[:url], :notice => "Signed in"
    end
  end
  
  def destroy
    session[:oauth_token] = nil
    session[:oauth_token_secret] = nil
    session[:username] = nil
    redirect_to root_url, :notice => "Signed out"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/janken_helper.rb
module JankenHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/janken/_form.html.erb
<%= form_for @janken, :html => { :class => "form-horizontal janken" } do |f| %>

    <% if @janken.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@janken.errors.count, "error") %> prohibited this janken from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @janken.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :user, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user, :class => 'form-control' %>
    </div>
    <%= error_span(@janken[:user]) %>
  </div>
  <div class="control-group">
    <%= f.label :enemy, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :enemy, :class => 'form-control' %>
    </div>
    <%= error_span(@janken[:enemy]) %>
  </div>
  <div class="control-group">
    <%= f.label :userhand, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :userhand, :class => 'form-control' %>
    </div>
    <%= error_span(@janken[:userhand]) %>
  </div>
  <div class="control-group">
    <%= f.label :enemyhand, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :enemyhand, :class => 'form-control' %>
    </div>
    <%= error_span(@janken[:enemyhand]) %>
  </div>
  <div class="control-group">
    <%= f.label :judge, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :judge, :class => 'form-control' %>
    </div>
    <%= error_span(@janken[:judge]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            jankens_path, :class => 'btn btn-default' %>

<% end %>

app/views/janken/battle.html.erb
<section class="container">
  <h1>受けて立つ！</h1>
  <h3>@<%= @enemy %>さん、@<%= @user %>さんからの挑戦だ！</h3>
    <%= form_tag({:action => "update_battle"}, 
      {:method => "post", :class => "form-horizontal"}) do %>
      <%= hidden_field_tag('id', @id) %>
      <div class='form-group'>
        <label class="control-label col-xs-2">手</label>
        <div class="col-xs-5">
          <%= number_field_tag('enemyhand', '0') %><br>
          グー:0 チョキ:1 パー:2
        </div>
      </div>

      <div class='form-group'>
        <div class="col-xs-offset-2 col-xs-10">
          <%= submit_tag("Poi!", :class => 'btn btn-primary btn-md') %>
        </div>
      </div>
    <% end %>
</section>

app/views/janken/edit.html.erb
<%- model_class = Janken -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/janken/index.html.erb
<%- model_class = Janken -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user) %></th>
      <th><%= model_class.human_attribute_name(:enemy) %></th>
      <th><%= model_class.human_attribute_name(:userhand) %></th>
      <th><%= model_class.human_attribute_name(:enemyhand) %></th>
      <th><%= model_class.human_attribute_name(:judge) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @jankens.each do |janken| %>
      <tr>
        <td><%= link_to janken.id, janken_path(janken) %></td>
        <td><%= janken.user %></td>
        <td><%= janken.enemy %></td>
        <td><%= janken.userhand %></td>
        <td><%= janken.enemyhand %></td>
        <td><%= janken.judge %></td>
        <td><%=l janken.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_janken_path(janken), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      janken_path(janken),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_janken_path,
            :class => 'btn btn-primary' %>

app/views/janken/input.html.erb
<section class="container">
  <h1>勝負だ！</h1>
    <%= form_tag({:action => "update"}, 
    {:method => "post", :class => "form-horizontal"}) do %>
      <div class='form-group'>
        <label class="control-label col-xs-2">対戦相手</label>
        <div class="col-xs-5">
          @<%= text_field_tag("enemyname") %>
        </div>
      </div>
      
      <div class='form-group'>
        <label class="control-label col-xs-2">手</label>
        <div class="col-xs-5">
          <%= number_field_tag('userhand', '0') %><br>
          グー:0 チョキ:1 パー:2
        </div>
      </div>

      <div class='form-group'>
        <div class="col-xs-offset-2 col-xs-10">
          <%= submit_tag("Poi!", :class => 'btn btn-primary btn-md') %>
        </div>
      </div>
    <% end %>
</section>

app/views/janken/new.html.erb
<%- model_class = Janken -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/janken/show.html.erb
<%- model_class = Janken -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user) %>:</strong></dt>
  <dd><%= @janken.user %></dd>
  <dt><strong><%= model_class.human_attribute_name(:enemy) %>:</strong></dt>
  <dd><%= @janken.enemy %></dd>
  <dt><strong><%= model_class.human_attribute_name(:userhand) %>:</strong></dt>
  <dd><%= @janken.userhand %></dd>
  <dt><strong><%= model_class.human_attribute_name(:enemyhand) %>:</strong></dt>
  <dd><%= @janken.enemyhand %></dd>
  <dt><strong><%= model_class.human_attribute_name(:judge) %>:</strong></dt>
  <dd><%= @janken.judge %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              jankens_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_janken_path(@janken), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              janken_path(@janken),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/janken/update.html.erb
<h1>勝負を申し込みました。</h1>

app/views/janken/update_battle.html.erb
<h1>勝負を受けて立ちました。</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jankens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="navbar navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Jankens", "/", :class => "navbar-brand"%>
        </div>
        <% if signed_in? %>
          <ul class="nav navbar-nav">
            <li>
              <a href="#">
                @<%= session[:username] %>
              </a>
            </li>
          </ul>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
            <li>
              <% if signed_in? %>
                <%= link_to "Sign out", "/signout" %>
              <% else %>
                <%= link_to "Sign in with Twitter", "/auth/twitter" %>
              <% end %>
            </li>
        </ul>
      </div>
    </div>
  </header>

  <%= yield %>
</body>
</html>